- name: Setup Linux Workstation
  hosts: localhost
  vars_files:
    - vars/packages.yaml
    - vars/common.yaml
  roles:
    - role: system
      become: true
      tags: ["system"]
    - role: development
      become: true
      tags: ["development"]
