- name: Install nvm and node
  import_tasks: node.yaml
  tags:
    - javascript
    - nvm
    - node
- name: Install terminal
  import_tasks: terminal.yaml
  tags:
    - starship
- name: Install NVIM
  import_tasks: nvim.yaml
  tags:
    - nvim
- name: Install RUST
  import_tasks: rust.yaml
  tags:
    - rust
